@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

LAYOUT_TOP_DOWN()

Container_Boundary(auth_container, "Auth Service", "Java", "Аутентификация и авторизация (JWT, OAuth2)"){
    Component(auth_api, "Auth API", "REST API", "Принимает логин/пароль, выдаёт токены (JWT/OIDC)")
    Component(user_store_client, "User Store Client", "Client", "Запрос профиля пользователя")
    Component(token_service, "Token Service", "Library/Component", "Генерация/валидация JWT, refresh tokens")
}

ComponentDb_Ext(ms_databse, "НСИ", "Service")
Component_Ext(ms_api_gateway, "API Gateway", "Service")
ComponentDb_Ext(ms_Redis, "Redis", "DB")


Rel(auth_api, user_store_client, "Использует")
Rel(auth_api, token_service, "Использует")
Rel(token_service, ms_Redis, "Сохраняет refresh token / статус отзыва")
BiRel(user_store_client, ms_databse, "Обращается", "JDBC")
Rel(ms_api_gateway, auth_api, "Обращается", "REST")


@enduml